#!/bin/bash
cp /home/ubuntu/play-java-1.0-SNAPSHOT/conf/application.conf.original /home/ubuntu/play-java-1.0-SNAPSHOT/conf/application.conf
IP=$(curl http://169.254.169.254/latest/meta-data/local-ipv4)
sed -i "s/localhost/$IP/g" /home/ubuntu/play-java-1.0-SNAPSHOT/conf/application.conf
rm /home/ubuntu/play-java-1.0-SNAPSHOT/RUNNING_PID
#echo $IP
cd /home/ubuntu/play-java-1.0-SNAPSHOT/bin
./play-java

